services:
  - type: web
    name: wrapper-backend
    env: python
    region: frankfurt
    plan: free
    branch: main
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash backend/start.sh
